### ISSUE TITLE
Send function realization

### ISSUE THREAD

**Issue by slim25** [ellysh/l2bot#5]
Where is realization of Send function in input.au3 file?

**Comment by ellysh** [comment]
The "Send" function is provided by AutoIt run-time library:
https://www.autoitscript.com/autoit3/docs/functions/Send.htm

You can use the "input_driver.au3" file instead of the "input.au3" one in case you want to simulate key presses via InpOut32 driver. This approach can be helpful to avoid protection systems in some servers.

**Comment by slim25** [comment]
Ok, thanx a lot!
